# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ipam_pb2 as ipam__pb2


class NmapServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IpSearch = channel.unary_unary(
                '/ipam.NmapService/IpSearch',
                request_serializer=ipam__pb2.IpRequest.SerializeToString,
                response_deserializer=ipam__pb2.IpDetail.FromString,
                )
        self.IpScan = channel.stream_unary(
                '/ipam.NmapService/IpScan',
                request_serializer=ipam__pb2.IpRequest.SerializeToString,
                response_deserializer=ipam__pb2.IpResponse.FromString,
                )


class NmapServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IpSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IpScan(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NmapServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IpSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.IpSearch,
                    request_deserializer=ipam__pb2.IpRequest.FromString,
                    response_serializer=ipam__pb2.IpDetail.SerializeToString,
            ),
            'IpScan': grpc.stream_unary_rpc_method_handler(
                    servicer.IpScan,
                    request_deserializer=ipam__pb2.IpRequest.FromString,
                    response_serializer=ipam__pb2.IpResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ipam.NmapService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NmapService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IpSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ipam.NmapService/IpSearch',
            ipam__pb2.IpRequest.SerializeToString,
            ipam__pb2.IpDetail.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IpScan(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/ipam.NmapService/IpScan',
            ipam__pb2.IpRequest.SerializeToString,
            ipam__pb2.IpResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
